from .base import db
from .goal import Goal
from .user import User
from .achievement import Achievement
from .activity import Activity
from .rating import Rating
from .competition import Competition
from .equipment import Equipment
from .database import app
