"""add speed to activity

Revision ID: 0d01bbe39805
Revises: fe9f2c931083
Create Date: 2026-04-17 10:57:28.668524

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0d01bbe39805'
down_revision = 'fe9f2c931083'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity', schema=None) as batch_op:
        batch_op.alter_column('time_s',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=3),
               existing_nullable=False)

    with op.batch_alter_table('challenge', schema=None) as batch_op:
        batch_op.alter_column('stroke',
               existing_type=postgresql.ENUM('FREESTYLE', 'BACKSTROKE', 'BREASTSTROKE', 'BUTTERFLY', name='stroke_type'),
               nullable=False)

    with op.batch_alter_table('rating', schema=None) as batch_op:
        batch_op.alter_column('value',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.alter_column('activity_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rating', schema=None) as batch_op:
        batch_op.alter_column('activity_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.alter_column('value',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=False)

    with op.batch_alter_table('challenge', schema=None) as batch_op:
        batch_op.alter_column('stroke',
               existing_type=postgresql.ENUM('FREESTYLE', 'BACKSTROKE', 'BREASTSTROKE', 'BUTTERFLY', name='stroke_type'),
               nullable=True)

    with op.batch_alter_table('activity', schema=None) as batch_op:
        batch_op.alter_column('time_s',
               existing_type=sa.Float(precision=3),
               type_=sa.REAL(),
               existing_nullable=False)

    # ### end Alembic commands ###
