"""+new enum and some change to equipmnet

Revision ID: 13feefb6df9c
Revises: 0d01bbe39805
Create Date: 2026-04-20 18:43:57.794769

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13feefb6df9c'
down_revision = '0d01bbe39805'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

       op.execute("CREATE TYPE equipment_type AS ENUM ('FLIPPERS', 'HAND_PADDLES', 'SNORKEL');")
       
       with op.batch_alter_table('activity', schema=None) as batch_op:
              batch_op.alter_column('time_s',
                     existing_type=sa.REAL(),
                     type_=sa.Float(precision=3),
                     existing_nullable=False)

       with op.batch_alter_table('equipment', schema=None) as batch_op:
           batch_op.add_column(sa.Column('type', sa.Enum('FLIPPERS', 'HAND_PADDLES', 'SNORKEL', name='equipment_type'), nullable=False))
           batch_op.add_column(sa.Column('is_broken', sa.Boolean(), server_default=sa.false(), nullable=False))
           batch_op.alter_column('name',
                  existing_type=sa.VARCHAR(length=20),
                  type_=sa.String(length=40),
                  nullable=False)
           batch_op.alter_column('brand',
                  existing_type=sa.VARCHAR(length=25),
                  type_=sa.String(length=50),
                  existing_nullable=True)
           batch_op.drop_column('typ')
           
       

       with op.batch_alter_table('rating', schema=None) as batch_op:
           batch_op.alter_column('value',
                  existing_type=sa.REAL(),
                  type_=sa.Float(precision=2),
                  existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rating', schema=None) as batch_op:
        batch_op.alter_column('value',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=False)

    with op.batch_alter_table('equipment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('typ', sa.VARCHAR(length=15), autoincrement=False, nullable=True))
        batch_op.add_column
        batch_op.alter_column('brand',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=25),
               existing_nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.String(length=40),
               type_=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.drop_column('type')

    with op.batch_alter_table('activity', schema=None) as batch_op:
        batch_op.alter_column('time_s',
               existing_type=sa.Float(precision=3),
               type_=sa.REAL(),
               existing_nullable=False)
        
    op.execute("DROP TYPE equipment_type;")
    # ### end Alembic commands ###
