"""Change value rating to float

Revision ID: 18adc53b58c3
Revises: e583cf1c9d0c
Create Date: 2026-04-15 10:57:31.014376

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18adc53b58c3'
down_revision = 'e583cf1c9d0c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rating', schema=None) as batch_op:
        batch_op.alter_column('value',
               existing_type=sa.INTEGER(),
               type_=sa.Float(precision=2),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rating', schema=None) as batch_op:
        batch_op.alter_column('value',
               existing_type=sa.Float(precision=2),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
