"""add challenge_id to achievement

Revision ID: 62769400f2ef
Revises: 675db0b0dfd3
Create Date: 2026-03-30 17:27:24.254726

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62769400f2ef'
down_revision = '675db0b0dfd3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('achievement', schema=None) as batch_op:
        batch_op.add_column(sa.Column('challenge_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'challenge', ['challenge_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('achievement', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('challenge_id')

    # ### end Alembic commands ###
