"""delete competition_id in achievement

Revision ID: 675db0b0dfd3
Revises: 9a85d802830e
Create Date: 2026-03-28 17:21:33.642556

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '675db0b0dfd3'
down_revision = '9a85d802830e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('achievement', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('achievement_competition_id_fkey'), type_='foreignkey')
        batch_op.drop_column('competition_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('achievement', schema=None) as batch_op:
        batch_op.add_column(sa.Column('competition_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key(batch_op.f('achievement_competition_id_fkey'), 'competition', ['competition_id'], ['id'])

    # ### end Alembic commands ###
