"""Add validates and Contsraints

Revision ID: 6f481bf56f61
Revises: 13feefb6df9c
Create Date: 2026-04-23 17:19:06.197203

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f481bf56f61'
down_revision = '13feefb6df9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity', schema=None) as batch_op:
        batch_op.alter_column('time_s',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=3),
               existing_nullable=False)

    with op.batch_alter_table('rating', schema=None) as batch_op:
        batch_op.alter_column('value',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=False)
        batch_op.create_unique_constraint('uq_rating_user_activity', ['user_id', 'activity_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rating', schema=None) as batch_op:
        batch_op.drop_constraint('uq_rating_user_activity', type_='unique')
        batch_op.alter_column('value',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=False)

    with op.batch_alter_table('activity', schema=None) as batch_op:
        batch_op.alter_column('time_s',
               existing_type=sa.Float(precision=3),
               type_=sa.REAL(),
               existing_nullable=False)

    # ### end Alembic commands ###
