"""Some changes in Challenge and delete User_Challenge

Revision ID: 9a85d802830e
Revises: 81e41f67c8d3
Create Date: 2026-03-28 17:13:40.220666

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9a85d802830e'
down_revision = '81e41f67c8d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_challenge')
    with op.batch_alter_table('challenge', schema=None) as batch_op:
        batch_op.drop_column('image')
        batch_op.drop_column('expired_at')
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('challenge', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('expired_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('image', sa.TEXT(), autoincrement=False, nullable=False))

    op.create_table('user_challenge',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('status', postgresql.ENUM('ACTIVE', 'FAILURE', 'COMPLETED', name='status'), autoincrement=False, nullable=False),
    sa.Column('compleated_at', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('challenge_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['challenge_id'], ['challenge.id'], name=op.f('user_challenge_challenge_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('user_challenge_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('user_challenge_pkey'))
    )
    # ### end Alembic commands ###
