"""Add competition_id to rating

Revision ID: d79444ed183c
Revises: 62769400f2ef
Create Date: 2026-04-01 12:33:04.317739

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd79444ed183c'
down_revision = '62769400f2ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rating', schema=None) as batch_op:
        batch_op.add_column(sa.Column('competition_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'competition', ['competition_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rating', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('competition_id')

    # ### end Alembic commands ###
