"""replace ahievement_id, challange_id,compet_id to model_name and refernse_id in rating

Revision ID: e583cf1c9d0c
Revises: ed3b0b19d61b
Create Date: 2026-04-14 17:34:16.031453

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e583cf1c9d0c'
down_revision = 'ed3b0b19d61b'
branch_labels = None
depends_on = None



    # ### commands auto generated by Alembic - please adjust! ###
  

    # ### end Alembic commands ###


from sqlalchemy.dialects import postgresql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DO $$ BEGIN CREATE TYPE modelname AS ENUM ('ACHIEVEMENT', 'ACTIVITY'); EXCEPTION WHEN duplicate_object THEN null; END $$;")

    with op.batch_alter_table('rating', schema=None) as batch_op:
        batch_op.add_column(sa.Column('model_name', sa.Enum('ACHIEVEMENT', 'ACTIVITY', name='modelname'), nullable=True))
        batch_op.add_column(sa.Column('referense_id', sa.Integer(), nullable=True))

    op.execute("UPDATE rating SET model_name = 'ACHIEVEMENT', referense_id = achievement_id WHERE achievement_id IS NOT NULL")

    with op.batch_alter_table('rating', schema=None) as batch_op:
        batch_op.alter_column('model_name', nullable=False)
        batch_op.alter_column('referense_id', nullable=False)
        batch_op.drop_constraint('rating_competition_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('rating_achievement_id_fkey', type_='foreignkey')
        batch_op.drop_column('competition_id')
        batch_op.drop_column('achievement_id')
        # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rating', schema=None) as batch_op:
        batch_op.add_column(sa.Column('achievement_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('competition_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('rating_achievement_id_fkey', 'achievement', ['achievement_id'], ['id'])
        batch_op.create_foreign_key('rating_competition_id_fkey', 'competition', ['competition_id'], ['id'])
    
    op.execute("UPDATE rating SET achievement_id = referense_id WHERE model_name = 'ACHIEVEMENT'")
    
    with op.batch_alter_table('rating', schema=None) as batch_op:
        batch_op.drop_column('referense_id')
        batch_op.drop_column('model_name')

    op.execute("DROP TYPE modelname")
    # ### end Alembic commands ###