"""+ status to competition

Revision ID: ed3b0b19d61b
Revises: d79444ed183c
Create Date: 2026-04-01 13:03:09.757083

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed3b0b19d61b'
down_revision = 'd79444ed183c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('competition', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.Enum('ACTIVE', 'FAILURE', 'COMPLETED', name='status'), server_default='ACTIVE', nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('competition', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
