"""Initial migration

Revision ID: fe0b99cdaea7
Revises: 
Create Date: 2026-03-28 11:30:25.949807

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe0b99cdaea7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('challenge',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('description', sa.String(length=110), nullable=True),
    sa.Column('image', sa.Text(), nullable=False),
    sa.Column('created_at', sa.Date(), nullable=False),
    sa.Column('expired_at', sa.Date(), nullable=False),
    sa.Column('distance', sa.Integer(), nullable=False),
    sa.CheckConstraint('expired_at >= CURRENT_DATE', name='ck_challange'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('competition',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=25), nullable=False),
    sa.Column('location', sa.String(length=100), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.CheckConstraint("location != ''", name='ck_competition_location'),
    sa.CheckConstraint("name != ''", name='ck_competition_name'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('token_block_list',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('jti', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=30), nullable=False),
    sa.Column('email', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('password_hash', sa.String(length=64), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'USER', name='userrole'), nullable=False),
    sa.Column('facebook_id', sa.String(length=100), nullable=True),
    sa.CheckConstraint("email LIKE '%%_@__%%.__%%'", name='ck_user_email_format'),
    sa.CheckConstraint("username != ''", name='ck_user_username_not_empty'),
    sa.CheckConstraint('age BETWEEN 5 and 100', name='ck_user_age'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('email', name='uq_user_email')
    )
    op.create_table('achievement',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('stroke', sa.Enum('FREESTYLE', 'BACKSTROKE', 'BREASTSTROKE', 'BUTTERFLY', name='stroke_type'), nullable=False),
    sa.Column('time', sa.Time(timezone=3), nullable=False),
    sa.Column('distance_meters', sa.Integer(), nullable=False),
    sa.Column('competition_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['competition_id'], ['competition.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('activity',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('day', sa.DateTime(timezone=True), nullable=False),
    sa.Column('stroke', sa.Enum('FREESTYLE', 'BACKSTROKE', 'BREASTSTROKE', 'BUTTERFLY', name='stroke_type'), nullable=False),
    sa.Column('distance_meters', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.CheckConstraint('distance_meters > 0 ', name='ck_activity_distance'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('goal',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('target_distance', sa.Integer(), nullable=False),
    sa.Column('deadline', sa.Date(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'FAILURE', 'COMPLETED', name='status'), nullable=False),
    sa.CheckConstraint('deadline >= CURRENT_DATE', name='ck_goal_deadline'),
    sa.CheckConstraint('target_distance > 0', name='ck_goal_target_distance'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_challenge',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'FAILURE', 'COMPLETED', name='status'), nullable=False),
    sa.Column('compleated_at', sa.Date(), nullable=True),
    sa.Column('challenge_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['challenge_id'], ['challenge.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('equipment',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=20), nullable=True),
    sa.Column('typ', sa.String(length=15), nullable=True),
    sa.Column('brand', sa.String(length=25), nullable=True),
    sa.Column('achievement_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['achievement_id'], ['achievement.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rating',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('achievement_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['achievement_id'], ['achievement.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rating')
    op.drop_table('equipment')
    op.drop_table('user_challenge')
    op.drop_table('goal')
    op.drop_table('activity')
    op.drop_table('achievement')
    op.drop_table('user')
    op.drop_table('token_block_list')
    op.drop_table('competition')
    op.drop_table('challenge')
    # ### end Alembic commands ###
