"""Change activity,rating,challenge and delete achievement

Revision ID: fe9f2c931083
Revises: 18adc53b58c3
Create Date: 2026-04-16 12:32:12.561898

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'fe9f2c931083'
down_revision = '18adc53b58c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    with op.batch_alter_table('activity', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('time_s', sa.Float(precision=3), nullable=False))
        batch_op.add_column(sa.Column('model_name', sa.Enum('CHALLENGE', 'GOAL', name='modelname'), nullable=False))
        batch_op.add_column(sa.Column('referense_id', sa.Integer(), nullable=False))
        batch_op.drop_column('day')
    
    with op.batch_alter_table('challenge', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stroke', sa.Enum('FREESTYLE', 'BACKSTROKE', 'BREASTSTROKE', 'BUTTERFLY', 'MIXED', name='stroke_type'), nullable=True))

    op.execute("UPDATE challenge SET stroke = 'FREESTYLE'")

    with op.batch_alter_table('challenge', schema=None) as batch_op:
        batch_op.alter_column(sa.Column('stroke', nullable=False))

    with op.batch_alter_table('equipment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('activity_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint(batch_op.f('equipment_achievement_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'activity', ['activity_id'], ['id'])
        batch_op.drop_column('achievement_id')

    with op.batch_alter_table('rating', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('activity_id', sa.Integer(), nullable=True))

    op.execute("UPDATE rating SET updated_at = CURRENT_TIMESTAMP , activity_id = 1")

    with op.batch_alter_table('rating', schema=None) as batch_op:
        batch_op.alter_column(sa.Column('updated_at', nullable=False))
        batch_op.alter_column(sa.Column('activity_id', nullable=False))
        batch_op.alter_column('value',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=False)
        batch_op.create_foreign_key(None, 'activity', ['activity_id'], ['id'])
        batch_op.drop_column('model_name')
        batch_op.drop_column('referense_id')
    op.drop_table('achievement')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rating', schema=None) as batch_op:
        batch_op.add_column(sa.Column('referense_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('model_name', postgresql.ENUM('ACHIEVEMENT', 'ACTIVITY', name='modelname'), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('value',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=False)
        batch_op.drop_column('activity_id')
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('equipment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('achievement_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('equipment_achievement_id_fkey'), 'achievement', ['achievement_id'], ['id'])
        batch_op.drop_column('activity_id')

    with op.batch_alter_table('challenge', schema=None) as batch_op:
        batch_op.drop_column('stroke')

    with op.batch_alter_table('activity', schema=None) as batch_op:
        batch_op.add_column(sa.Column('day', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
        batch_op.drop_column('referense_id')
        batch_op.drop_column('model_name')
        batch_op.drop_column('time_s')
        batch_op.drop_column('created_at')

    op.create_table('achievement',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('stroke', postgresql.ENUM('FREESTYLE', 'BACKSTROKE', 'BREASTSTROKE', 'BUTTERFLY', name='stroke_type'), autoincrement=False, nullable=False),
    sa.Column('time', postgresql.TIME(timezone=True), autoincrement=False, nullable=False),
    sa.Column('distance_meters', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('challenge_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['challenge_id'], ['challenge.id'], name=op.f('achievement_challenge_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('achievement_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('achievement_pkey'))
    )
    # ### end Alembic commands ###
